// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtcvyrqwmurcdjwgxyfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Y3Z5cnF3bXVyY2Rqd2d4eWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDIyOTYsImV4cCI6MjA1ODExODI5Nn0.f8ykKxdaYUkUDseRxg4G9_mLUNKIr77fLcDptmvNw_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);